function metadata = get_controller_metadata(controller_name, PID_manual, opt_PID, LQR_manual, Q_opt, R_opt, K_manual, K_opt)
% Returns controller gain metadata for storing inside metrics_summary

    switch controller_name
        case 'PID Manual'
            metadata = struct( ...
                'Kp', PID_manual.Kp, ...
                'Ki', PID_manual.Ki, ...
                'Kd', PID_manual.Kd);

        case 'PID Optimized'
            metadata = struct( ...
                'Kp', opt_PID(1), ...
                'Ki', opt_PID(2), ...
                'Kd', opt_PID(3));

        case 'LQR Manual'
            metadata = struct( ...
                'Q', LQR_manual.Q, ...
                'R', LQR_manual.R, ...
                'K', K_manual);

        case 'LQR Optimized'
            metadata = struct( ...
                'Q', Q_opt, ...
                'R', R_opt, ...
                'K', K_opt);

        otherwise
            metadata = struct();
    end
end
